USE ENGRISK;
-- LESSON PROGRESS
ALTER TABLE LESSON_PROGRESS
ADD PRIMARY KEY (user_name, course_name);

ALTER TABLE USER
ADD INDEX idx_user_name (user_name);
ALTER TABLE LESSON_PROGRESS
ADD FOREIGN KEY (user_name) REFERENCES USER(user_name);

ALTER TABLE LESSON_PROGRESS
ADD FOREIGN KEY (course_name) REFERENCES COURSES(course_name);

ALTER TABLE LESSON_PROGRESS
ADD FOREIGN KEY (user_name) REFERENCES USER(user_name);

-- PROGRESS
ALTER TABLE PROGRESS
ADD PRIMARY KEY (user_name, course_name);

ALTER TABLE PROGRESS
ADD FOREIGN KEY (user_name) REFERENCES USER(user_name);

-- COURSES
ALTER TABLE COURSES
ADD PRIMARY KEY (course_name);

-- JOIN COURSE
ALTER TABLE JOIN_COURSE
ADD PRIMARY KEY (user_name, course_name);

ALTER TABLE JOIN_COURSE
ADD FOREIGN KEY (user_name) REFERENCES USER(user_name);

-- USER
ALTER TABLE USER
ADD PRIMARY KEY(user_name);

-- CONFIG VOCAB AND GRAMMAR
ALTER TABLE VOCAB
ADD COLUMN course_type VARCHAR(255);


SET SQL_SAFE_UPDATES = 0;

ALTER TABLE VOCAB
ADD FOREIGN KEY (course_type) REFERENCES COURSES(category);

ALTER TABLE GRAMMAR
ADD COLUMN course_type VARCHAR(255);

ALTER TABLE GRAMMAR
ADD FOREIGN KEY (course_type) REFERENCES COURSES(category);

-- CONTRIBUTE
ALTER TABLE CONTRIBUTE
ADD FOREIGN KEY(user_name) REFERENCES USER(user_name);
ALTER TABLE CONTRIBUTE
ADD FOREIGN KEY(words) REFERENCES VOCAB(words)


UPDATE VOCAB
SET course_type = 'GRAMMAR'