CREATE DATABASE ENGRISK;

USE ENGRISK;

CREATE TABLE VOCAB(
	category VARCHAR(255) NOT NULL, -- Job, Tech,..
	words VARCHAR(255) NOT NULL PRIMARY KEY,
	wordType VARCHAR(10) NOT NULL,
	pronoun VARCHAR(255) NOT NULL,
	exampleSentence VARCHAR(255) NOT NULL
);

CREATE TABLE GRAMMAR(
	category VARCHAR(255) NOT NULL,
	grammarType VARCHAR(255) NOT NULL PRIMARY KEY,
	usingSituation VARCHAR(255) NOT NULL,
	positiveFormula VARCHAR(255) NOT NULL,
	negativeFormula VARCHAR(255) NOT NULL,
	questionFormula VARCHAR(255) NOT NULL,
	exampleSentence VARCHAR(255) NOT NULL
);

USE ENGRISK;
SELECT * FROM VOCAB


